### ISSUE TITLE
Highest level of Education re-work

### ISSUE THREAD

**Issue by sroth88** [SuffolkLITLab/docassemble-AffidavitOfIndigencySupplement#23]
The form needs an option for "other" or at least a field where the user can type in their answer. There may be levels of education that don't exactly fit into our provided choices.

**Comment by CaroRob** [comment]
American Community Survey (Census Bureau) question is

**What is the highest degree or level of school Caroline G Robinson has COMPLETED?** _If currently enrolled, select the previous grade or highest degree received._ **(Help - with COVID-19 guidance)**

NO SCHOOLING COMPLETED
- No schooling completed

NURSERY OR PRESCHOOL THROUGH GRADE 12
- Nursery School
- Kindergarten
- Grade 1 through 11 - Specify grade 1-11
_text box  here to fill in grade_
- 12th grade - NO DIPLOMA

HIGH SCHOOL GRADUATE
- Regular high school diploma
- GED or alternative credential

COLLEGE OR SOME COLLEGE
- Some college credit, but less than 1 year of college credit
- 1 or more years of college credit, no degree
- Associate's degree (for example: AA, AS)
- Bachelor's degree (for example: BA, BS)

AFTER BACHELOR'S DEGREE
- Master's degree (for example: MA, MS, MEng, MEd, MSW, MBA)
- Professional degree beyond a bachelor's degree (for example: MD, DDS, DVM, LLB, JD)
- Doctorate degree (for example: PhD, EdD) 

I just thought I would stick this in here as an example to consider

**Comment by dahlerik** [comment]
Thanks for the exhaustive list.

What do we want on our form?

The question uses radio buttons. Which bullet points should we include?
