### ISSUE TITLE
Dependents change

### ISSUE THREAD

**Issue by sroth88** [SuffolkLITLab/docassemble-AffidavitOfIndigencySupplement#26]
Change title to "How many dependents do you have?" and change the numbered input field to a text field to allow the user to explain their potential dependents if they choose to do so.

**Comment by BryceStevenWilley** [comment]
Looked into this more: 

In the PDF, `user_dependents_number` says "the number of dependents". However, the main Affidavit form says, 

> a household of __ persons, consisting of myself and __ dependents

implying that according to the MA Affidavit forms, everyone else in the household (besides yourself) is considered a dependent. This is different from the tax wording of dependent, where others would be actually dependent on you.

There are references in the main Affidavit that this number is used for federal poverty guidelines, which also only considers whole household size and whole household income, not dependent count; this cements further that we should be asking for household size, borrowing the language from the main affidavit.

**Comment by BryceStevenWilley** [comment]
With #46, this has been aligned with the main affidavit's wording, and should probably stay the same. Going to close this.
