### ISSUE TITLE
Improve `there_are_any` accounts question

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AffidavitOfIndigencySupplement#33]
Improve `there_are_any` accounts question

_Originally posted by @plocket in https://github.com/SuffolkLITLab/docassemble-AffidavitOfIndigencySupplement/pull/32#discussion_r482128345_

**Comment by dahlerik** [comment]
fix idea: 

control screen with questions for each type of account. (List of types suggested by @CaroRob) .
question: use yesnowide or checkbox?

if user says yes to an account type, trigger list collect for that account type.
list collect only asks for value, type preset by control question.

**Comment by dahlerik** [comment]
remove unnecessary list questions for bank account. I think there are at least two.
