### ISSUE TITLE
Other Expenses Screen Order

### ISSUE THREAD

**Issue by sroth88** [SuffolkLITLab/docassemble-AffidavitOfIndigencySupplement#4]
The form will ask the user if they have any other expenses that they would like to record, aside from the expenses that the form explicitly asks for. We have had two ideas about where to put this screen after we implemented the checkboxes into the "expenses" questions. The first option would be to add the "other expenses" as an optional button for the checkboxes and then conditionally ask the user about their other expenses at the end. The second option would be to not include an "other expenses" button and automatically ask about their other expenses at the end. 

The third thought of ours was to add a "review" screen that shows all of their expenses, including the ones they did not check off, and allow them to edit/add other expenses on that screen.

**Comment by dahlerik** [comment]
idea: after user selects expenses categories, show them what they selected, then ask if any other expenses, for example diapers.
After this, ask for amounts.
